<a href="https://colab.research.google.com/github/pratikdash07/Capg_ML/blob/main/06_02_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [ ]:
import numpy as np

In [ ]:
# # Syntax for creation of array

# # var_name = np.array((c1, 2, 3)) #list,tuple can be given as the input to create an array
# # var_name

# # var_name = np.array((1,2,3, {1,2,3})) # nesting is running with set but data type is an 'object'
# # print(type(var_name))
# # print(var_name)
# # print(var_name.dtype) # Datatype of array

# var_name = np.array((True,2.3,2+6j,'strng'))
# print(type(var_name))
# print(var_name)
# print(var_name.dtype) # Datatype of array ().dtype is a property of array)

# #Upcasting : Array is homogenous but if it is provided with a different data type, it will not throw an error but it will do upcasting.
# # bool --> int --> float --> complex --> str --> set --> dict
# #Upcasting is done in this flow




<class 'numpy.ndarray'>
['True' '2.3' '(2+6j)' 'strng']
<U64


In [ ]:
# # ##Vectorization : the practice of performing operations on entire
# # #arrays at once rather than iterating through individual elements using explicit Python loops

# # arr = np.array([1,2,3,4,5])
# # arr +1
# # arr -1
# # arr *2
# # arr /2
# # arr //2
# # arr **2
# arr%2

array([1, 0, 1, 0, 1])

In [ ]:
#Broadcasting  : It is used to add arrays, arrays should be of same dimension or of one dimension,
#if they are different, it will be checked from  right to left

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

a1+a2 #works if the dimensions are same
#a1+a2
d2+d3

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [ ]:
##Properties
dt  = np.array([1,2,3,5,6])
dt.dtype # to know the datasize
#2
dt.shape #number of elements
#3
dt.ndim #dimension of array
#4
dt.size #total number of elements

1

In [ ]:
##2d array
d2 = np.array([[1,2,3],
              [4,5,6],
               [7,8,9]])
print(d2)
print(d2.ndim)
print(d2.dtype)
print(d2.shape) #row,col
print(d2.size)
print("""
          """)


d3 = np.array([[[1,2,3],
              [4,5,6],
               [7,8,9]],
                [[1,2,3],
                 [4,5,6],
                  [7,8,9]]])
print(d3)
print(d3.ndim)
print(d3.dtype)
print(d3.shape)
print(d3.size)


d4 = np.array([[[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]],
                [[[9, 10], [11, 12]],
                 [[13, 14], [15, 16]]]])

print(d4)
print(d4.ndim)
print(d4.dtype)
print(d4.shape)
print(d4.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
int64
(3, 3)
9

          
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
int64
(2, 3, 3)
18
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
4
int64
(2, 2, 2, 2)
16


In [ ]:
#Indexing and Slicing in Array in different dimension arrays
d1 = np.array([1,2,3])
d1[0]
d1[-1]
d2[2,-1]
d2[0][0]
d2[0,0]

d3[0,1,1]
d3[0][0][1]

np.int64(2)

In [ ]:

##SLICING
#syntax
#Collection[startind:endind:step/update]

# startind = inclusive
# endind = exclusive
# step = +ve and -ve

# l = [1,2,3,4]
# l[1:3:1]
# l[1:3]
# l[1::2]
# l[::-1]


d1 = np.array([1,2,3,4,5])
d1[2:4:1]
d1[2:4]




d2[1:,2]
d2[:,1:]




array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
# Original 3D array d3
print("Original d3 array:")
print(d3)

# 1. Access the second 2D array (index 1 along the first axis)
print("\nAccessing the second 2D array (d3[1]):")
print(d3[1])

# 2. Access the first row of all 2D arrays (across the second axis)
print("\nAccessing the first row across all 2D arrays (d3[:, 0, :]):")
print(d3[:, 0, :])

# 3. Access the last column of all 2D arrays (across the third axis)
print("\nAccessing the last column across all 2D arrays (d3[:, :, -1]):")
print(d3[:, :, -1])
# 4. Extract a sub-block: from the first 2D array, take the first two rows and first two columns
print("\nExtracting a sub-block (d3[0, :2, :2]):")
print(d3[0, :2, :2])

# 5. Extract elements using a step (e.g., every other column from all 2D arrays)
print("\nExtracting every other column from all 2D arrays (d3[:, :, ::2]):")
print(d3[:, :, ::2])



Original d3 array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

Accessing the second 2D array (d3[1]):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Accessing the first row across all 2D arrays (d3[:, 0, :]):
[[1 2 3]
 [1 2 3]]

Accessing the last column across all 2D arrays (d3[:, :, -1]):
[[3 6 9]
 [3 6 9]]

Extracting a sub-block (d3[0, :2, :2]):
[[1 2]
 [4 5]]

Extracting every other column from all 2D arrays (d3[:, :, ::2]):
[[[1 3]
  [4 6]
  [7 9]]

 [[1 3]
  [4 6]
  [7 9]]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(d3[0][:,1][2])
print(d3[1][:,2])
print(d3[:,:,2])

8
[3 6 9]
[[3 6 9]
 [3 6 9]]


In [ ]:
#Key functions used in numpy
###np.arange()


range(10)
np.arange(1,10,0.5) # for step, np.arange accepts step as floating point step values
###np.zeros()
zeros = np.array(np.zeros((3,3)))
zeros

np.zeros((2,2,2,3,4))
np.zeros(8)
###np.ones() #Fill array with 1

np.ones(3)
np.ones((3,3))

##np.full() #fill array with customized value
np.full((3,3,3),5)

##np.linspace(strval,endval,value) #It creates qequispaced vals between a range. Create one dimensional array
np.linspace(1,10,5)

#np.eye(): Create an identity matrix
np.eye(7)

#np.random.randint()
np.random.randint(1,10,(2,3,4))


##STATISTICAL FUNCTIONS
#mean,median,mode,variance,standard deviation,avg,sum
np.mean(d1)
d1
np.sum(d1)
d1.size

np.std(d1)

np.median(t)

np.average()

np.reshape(-1) #Flatten any dimensional array into 1d array

NameError: name 't' is not defined